// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cv-service/internal/controllers"
	"cv-service/internal/grpc/client"
	"cv-service/internal/repositories"
	"cv-service/internal/services"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// Return pointer, not value
func InitializeRecommendationHistoryDependency(db *gorm.DB, authClient *client.AuthClient) *controllers.RecommendationHistoryController {
	recommendationHistoryRepo := repositories.NewRecommendationHistoryRepo(db)
	recommendationHistoryService := services.NewRecommendationHistoryService(recommendationHistoryRepo)
	recommendationHistoryController := controllers.NewRecommendationHistoryController(recommendationHistoryService, authClient)
	return recommendationHistoryController
}

// wire.go:

var SuperSet = wire.NewSet(repositories.NewRecommendationHistoryRepo, services.NewRecommendationHistoryService, controllers.NewRecommendationHistoryController)
