// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: proto/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Guard         string                 `protobuf:"bytes,2,opt,name=guard,proto3" json:"guard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequestRequest) Reset() {
	*x = ValidateRequestRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequestRequest) ProtoMessage() {}

func (x *ValidateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequestRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequestRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateRequestRequest) GetGuard() string {
	if x != nil {
		return x.Guard
	}
	return ""
}

type ValidateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequestResponse) Reset() {
	*x = ValidateRequestResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequestResponse) ProtoMessage() {}

func (x *ValidateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequestResponse.ProtoReflect.Descriptor instead.
func (*ValidateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRequestResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateRequestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAuthIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Guard         string                 `protobuf:"bytes,2,opt,name=guard,proto3" json:"guard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthIDRequest) Reset() {
	*x = GetAuthIDRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthIDRequest) ProtoMessage() {}

func (x *GetAuthIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthIDRequest.ProtoReflect.Descriptor instead.
func (*GetAuthIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthIDRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetAuthIDRequest) GetGuard() string {
	if x != nil {
		return x.Guard
	}
	return ""
}

type GetAuthIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthIDResponse) Reset() {
	*x = GetAuthIDResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthIDResponse) ProtoMessage() {}

func (x *GetAuthIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthIDResponse.ProtoReflect.Descriptor instead.
func (*GetAuthIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthIDResponse) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *GetAuthIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_auth_auth_proto protoreflect.FileDescriptor

const file_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x15proto/auth/auth.proto\x12\x04auth\"D\n" +
	"\x16ValidateRequestRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05guard\x18\x02 \x01(\tR\x05guard\"E\n" +
	"\x17ValidateRequestResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x10GetAuthIDRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05guard\x18\x02 \x01(\tR\x05guard\"B\n" +
	"\x11GetAuthIDResponse\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x9b\x01\n" +
	"\vAuthService\x12N\n" +
	"\x0fValidateRequest\x12\x1c.auth.ValidateRequestRequest\x1a\x1d.auth.ValidateRequestResponse\x12<\n" +
	"\tGetAuthID\x12\x16.auth.GetAuthIDRequest\x1a\x17.auth.GetAuthIDResponseBCZAgithub.com/agusheryanto182/job-recommendations/backend/proto/authb\x06proto3"

var (
	file_proto_auth_auth_proto_rawDescOnce sync.Once
	file_proto_auth_auth_proto_rawDescData []byte
)

func file_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)))
	})
	return file_proto_auth_auth_proto_rawDescData
}

var file_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_auth_auth_proto_goTypes = []any{
	(*ValidateRequestRequest)(nil),  // 0: auth.ValidateRequestRequest
	(*ValidateRequestResponse)(nil), // 1: auth.ValidateRequestResponse
	(*GetAuthIDRequest)(nil),        // 2: auth.GetAuthIDRequest
	(*GetAuthIDResponse)(nil),       // 3: auth.GetAuthIDResponse
}
var file_proto_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.ValidateRequest:input_type -> auth.ValidateRequestRequest
	2, // 1: auth.AuthService.GetAuthID:input_type -> auth.GetAuthIDRequest
	1, // 2: auth.AuthService.ValidateRequest:output_type -> auth.ValidateRequestResponse
	3, // 3: auth.AuthService.GetAuthID:output_type -> auth.GetAuthIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_proto_init() }
func file_proto_auth_auth_proto_init() {
	if File_proto_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_auth_proto = out.File
	file_proto_auth_auth_proto_goTypes = nil
	file_proto_auth_auth_proto_depIdxs = nil
}
