# Development stage
FROM golang:1.24-alpine

RUN apk add --no-cache \
    git \
    bash \
    curl \
    make \
    protoc \        
    protobuf-dev && \
    go install github.com/air-verse/air@latest && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

WORKDIR /app

# Copy proto files FIRST
COPY backend/proto /app/proto

# Then copy service files
COPY backend/auth-service/go.mod backend/auth-service/go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

EXPOSE 8080 50051

ENTRYPOINT go mod download && ./scripts/build.sh && ./bin/migrate up && air