// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"auth-service/internal/controllers"
	"auth-service/internal/repositories"
	"auth-service/internal/services"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// Return pointer ke AuthController, bukan value
func InitializeUserDependency(db *gorm.DB) *controllers.AuthController {
	userRepo := repositories.NewUserRepo(db)
	authService := services.NewAuthService(userRepo)
	authController := controllers.NewAuthController(authService)
	return authController
}

// wire.go:

var SuperSet = wire.NewSet(repositories.NewUserRepo, services.NewAuthService, controllers.NewAuthController)
